name: "Notify"
description: "Notify about new PRs/issues/discussions via MS Teams"
inputs:
  webhook_url:
    description: "MS Teams Webhook URL"
    required: true
  prCondition:
    description: "When to notify about a PR."
    default: "onlyExternal"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
